name: Pipeline de Integração Contínua (CI)

on:
  push:
    branches: [ main, aula-08 ]
  pull_request:
    branches: [ main, aula-08 ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov

    - name: Executar todos os testes com Cobertura
      run: |
        python -m pytest -v --cov=models --cov=services